spring:
  application:
    name: aplus-cms-oms
baseUrl: D:\filepath\
##======================guns配置=================#
#aplus:
#  swagger-open: true #是否开启swagger (true/false)
#  kaptcha-open: false #是否开启登录时验证码 (true/false)
#  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
# #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
#  muti-datasource-open: false #是否开启多数据源(true/false)
#  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
#  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
#  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
#  cms:
#    adv: 
#      picurl: http://172.18.50.71:7001/h5web/rc
#
##======================项目启动端口配置=================#
#server:
#  port: 7028
#  
#  
##======================注册中心配置=================#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://guest:phfund@172.19.56.130:8761/eureka/
#  instance:
#    metadata-map:
#      env: dev
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#      
##======================beetl配置=================#
#beetl:
#  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
#  delimiter-statement-end: null
#  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
#  resource-tagsuffix: tag
#  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false
#
##======================spring配置=================#
#spring:
#  application:
#    name: aplus-cms-oms
#  data:
#    mongodb:
#      host: 172.18.50.114 
#      port: 27017
#      database: admin
#      username: admin
#      password: admin
#  # redis
#  redis: 
#    host: 172.18.50.115
#    port: 6379 
#    password: phFUND_linux_redis # 密码（默认为空）
#    timeout: 6000   # 连接超时时长（毫秒）
#    pool: 
#      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 10      # 连接池中的最大空闲连接
#      min-idle: 5       # 连接池中的最小空闲连接
#  # rabbitmq
#  rabbitmq:
#    host: 172.18.50.115
#    port: 5672
#    username: app
#    password: app123
#    virtual-host: vhost_filebroker
#  profiles:
#    active: dev
#  session: 
#    store-type: redis
#  # web
#  mvc:
#    static-path-pattern: /static/**
#    view:
#      prefix: WEB-INF/view
#      suffix: 
#  http:
#    converters:
#      preferred-json-mapper: fastjson
#    multipart:
#      max-request-size: 100MB #最大请求大小
#      max-file-size: 100MB #最大文件大小
#  devtools:
#    restart:
#      enabled: false #是否开启开发者工具（true/false）
#      additional-paths: src/main/java
#      exclude: static/**,WEB-INF/view/**
#  aop:
#    proxy-target-class: true
#  cloud:
#    config:
#      discovery:
#        service-id:
#      label: #false为启用jdk默认动态代理,true为cglib动态代理
#
##======================mybatis-plus配置=================#
#mybatis-plus: 
#  mapper-locations: classpath*:com/phfund/aplus/**/oms/**/mapping/*.xml
#  typeAliasesPackage: com.phfund.aplus.oms.camp.common.persistence.model
#  global-config:
#    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
#    db-column-underline: false
#    refresh-mapper: true
#  configuration:
#    map-underscore-to-camel-case: false
#    cache-enabled: true #配置的缓存的全局开关
#    lazyLoadingEnabled: true #延时加载的开关
#    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
#
#---
#
##======================开发环境的profile=================#
#spring:
#  profiles: dev
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.19.56.127:3306/aplus_camp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: aplus_camp
#    password: AplusCamp123
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    db-name: aplus_camp
#    filters: log4j,wall,mergeStat
## 多数据源配置
#aplus: 
#  flowable:
#    datasource:
#      url: jdbc:mysql://172.19.56.127:3306/aplus_camp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#      username: aplus_camp
#      password: AplusCamp123
#  muti-datasource:
#    default-dataSource-name: dataSourceGuns #默认的数据源名称
#    url: jdbc:mysql://172.19.56.127:3306/aplus_camp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: aplus_camp
#    password: AplusCamp123
#
#    
#
#logging:
#  level.root: info
#  level.com.phfund: debug
#  path: logs/
#  file: aplus.log
#
#---
#
##======================生产环境的profile=================#
#spring:
#  profiles: produce
#  datasource:
#      url: jdbc:mysql://172.19.56.127:3306/aplus_camp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#      username: aplus_camp
#      password: AplusCamp123
#      driver-class-name: com.mysql.jdbc.Driver
#      db-name: aplus-oms
#      filters: log4j,wall,mergeStat
#
#logging:
#  level.root: warn
#  path: logs/
#  file: aplus.log
#  
  
    
      
